### ISSUE TITLE
no such module Alamofire

### ISSUE THREAD

**Issue by aihui1983** [powhu/Shinsi#1]
After pod install ,When I try to building,xcode report 'no such module Alamofire'.
Could you give some help?

**Comment by powhu** [comment]
What version of Cocoapods?

`pod --version`

**Comment by aihui1983** [comment]
The version is 0.39.0.

**Comment by powhu** [comment]
uh...
I have tried again myself and it's working. 

Maybe you can try
`pod install --verbose`
to see any error here?
